version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praktikum2_app
    ports:
      - "8082:8000"
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    networks:
      - laravel_net
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: praktikum2_db
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  db_data:
